name: Elixir CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-elixir@2e0500f2a50c7f883e15eb4d0fa7dc15d2c458c1
        with:
          elixir-version: "1.12.1"
          otp-version: "24.0.3"
      - name: Restore dependencies cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-v1-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-v1-mix-
      - name: Install Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile
          mix dialyzer --plt
      - name: Run tests
        run: mix test
      - name: Static code quality checks
        run: |
          mix format --check-formatted
          mix credo
          mix dialyzer
      - name: Code Annotations Report
        if: ${{ always() }}
        uses: mikepenz/action-junit-report@v3.0.3
        with:
          report_paths: "reports/junit/*.xml"
          github_token: ${{ secrets.GITHUB_TOKEN }}
