name: Elixir CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        elixir-version: '1.12.2' 
        otp-version: '24.3' 
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
    - name: Static code quality checks
      run: |
        mix format --check-formatted
        mix credo
    - name: Code Annotations Report
      if: ${{ always() }}
      uses: mikepenz/action-junit-report@v1
      with:
        report_paths: "reports/junit/*.xml"
        github_token: ${{ secrets.GITHUB_TOKEN }}
